apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: tasker-app
spec:
  containers:
    - image: mongo:3.6
      name: mongo-pod
      ports:
       - name: mongo-port
         containerPort: 27017